import { connectDB } from "@/lib/db";
import { QuizModel } from "@/lib/schema";
import Link from "next/link";
import { BookOpen, Calendar, ChevronRight } from "lucide-react";
import { formatDistanceToNow } from "date-fns";

export const dynamic = "force-dynamic";

export default async function QuizzesPage() {
  await connectDB();
  const allQuizzes = (await QuizModel.find({}).lean()).map((q: any) => ({ ...q, id: q._id }));

  return (
    <div className="p-8 h-full flex flex-col max-w-5xl mx-auto w-full">
      <div className="mb-8">
        <h1 className="text-3xl font-heading font-bold text-white">Knowledge Checks</h1>
        <p className="text-slate-400 mt-2">Active learning modules generated by the QuestionGen Agent.</p>
      </div>

      {allQuizzes.length === 0 ? (
        <div className="flex-1 flex flex-col items-center justify-center glass border border-white/10 rounded-3xl p-12">
          <BookOpen className="w-16 h-16 text-slate-500 mb-4" />
          <h2 className="text-xl font-medium text-slate-300">No Quizzes Available</h2>
          <p className="text-slate-500 mt-2 text-center max-w-md">Upload a document to the system and the QuestionGen agent will automatically construct personalized quizzes.</p>
          <Link href="/upload" className="mt-6 px-6 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg transition-colors">Upload Document</Link>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {allQuizzes.map((q) => (
            <Link key={q.id} href={`/quiz/${q.id}`}>
              <div className="glass border border-white/10 hover:border-indigo-500/50 p-6 rounded-2xl transition-all group hover:bg-white/5">
                <div className="w-12 h-12 bg-white/5 text-indigo-400 rounded-xl flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                  <BookOpen className="w-6 h-6" />
                </div>
                <h3 className="text-lg font-semibold text-slate-200 line-clamp-1">{q.topic}</h3>
                <div className="flex items-center gap-2 mt-4 text-xs font-medium text-slate-500">
                  <Calendar className="w-4 h-4" />
                  {formatDistanceToNow(new Date(String(q.createdAt)), { addSuffix: true })}
                </div>
                <div className="mt-4 pt-4 border-t border-white/10 flex justify-between items-center text-sm font-medium text-indigo-400 opacity-0 group-hover:opacity-100 transition-opacity">
                  <span>Start Quiz</span> <ChevronRight className="w-4 h-4" />
                </div>
              </div>
            </Link>
          ))}
        </div>
      )}
    </div>
  );
}
